"""empty message

Revision ID: 2a7645cd6b2d
Revises: 13e72bd522f3
Create Date: 2018-03-09 16:50:44.377672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a7645cd6b2d'
down_revision = '13e72bd522f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_seen')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_seen', sa.DATETIME(), nullable=True))
    # ### end Alembic commands ###
