"""empty message

Revision ID: 033b71759f64
Revises: 84c37432c490
Create Date: 2018-04-02 17:58:35.075615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '033b71759f64'
down_revision = '84c37432c490'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'userkeys', type_='foreignkey')
    op.create_foreign_key(None, 'userkeys', 'users', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint(None, 'usertohosts', type_='foreignkey')
    op.drop_constraint(None, 'usertohosts', type_='foreignkey')
    op.create_foreign_key(None, 'usertohosts', 'hosts', ['host_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'usertohosts', 'users', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usertohosts', type_='foreignkey')
    op.drop_constraint(None, 'usertohosts', type_='foreignkey')
    op.create_foreign_key(None, 'usertohosts', 'hosts', ['host_id'], ['id'])
    op.create_foreign_key(None, 'usertohosts', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'userkeys', type_='foreignkey')
    op.create_foreign_key(None, 'userkeys', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
