"""empty message

Revision ID: 84c37432c490
Revises: 97b981ba974d
Create Date: 2018-03-29 19:53:31.082592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84c37432c490'
down_revision = '97b981ba974d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('qqnumber', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'qqnumber')
    # ### end Alembic commands ###
