"""empty message

Revision ID: af7e34b61262
Revises: 67c79aa93076
Create Date: 2018-03-07 16:53:58.353176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af7e34b61262'
down_revision = '67c79aa93076'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hostgroup', sa.Column('moMent', sa.String(length=128), nullable=True))
    op.add_column('roles', sa.Column('moMent', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'moMent')
    op.drop_column('hostgroup', 'moMent')
    # ### end Alembic commands ###
